-- =====================================================================
-- Game Development Tools Knowledge Bank — v1 SEED DATA
-- Run AFTER 01_schema.sql:
--   psql "$DATABASE_URL" -f 02_seed.sql
-- FK ids are resolved by slug subquery so this script is id-agnostic.
-- RE-RUNNABLE: a leading TRUNCATE … CASCADE clears the catalog first, so the
-- file can be applied any number of times (CI, docker first-boot, or by hand)
-- and always reasserts exactly this data. Runs in one transaction.
--
-- Coverage: 26 tools spanning game engines (incl. no-code: Construct 3,
-- GDevelop, Twine, RPG Maker), frameworks/libraries, asset creators,
-- audio middleware, and asset marketplaces. Per the request, marketplace
-- variants are modelled as SEPARATE entities from their engines
-- (Unity Asset Store ≠ Unity; Fab ≠ Unreal Engine) and linked by edges.
--
-- NOTES ON DATA QUALITY:
--   * confirmed_commercial_titles_count values are ILLUSTRATIVE
--     placeholders — replace with real, sourced figures (+ as_of date).
--   * licensing_note text reflects publicly documented terms as of
--     2026-07; the curator should re-verify before publishing.
--   * game_store_link URLs use well-known Steam app ids; verify per title.
-- =====================================================================

BEGIN;

-- 0) RESET: clear the catalog so this file is re-runnable. These five roots
-- CASCADE to every join / link / relationship table, and RESTART IDENTITY
-- resets the id sequences (safe — everything external keys off slugs).
TRUNCATE tool, area_of_use, platform, language, game RESTART IDENTITY CASCADE;

-- 1) AREA OF USE (parents first, then leaves) -----------------------------
INSERT INTO area_of_use (slug, name) VALUES
  ('asset_creation','Asset Creation'), ('audio','Audio'),
  ('world_building','World Building'), ('programming','Programming'),
  ('networking','Networking'), ('production','Production'),
  ('ui_ux','UI / UX'), ('distribution','Distribution'),
  ('development','Development');

INSERT INTO area_of_use (slug, name, parent_id) VALUES
  ('3d_modelling','3D Modelling',        (SELECT id FROM area_of_use WHERE slug='asset_creation')),
  ('2d_art','2D Art',                    (SELECT id FROM area_of_use WHERE slug='asset_creation')),
  ('pixel_art','Pixel Art',              (SELECT id FROM area_of_use WHERE slug='asset_creation')),
  ('texturing','Texturing',              (SELECT id FROM area_of_use WHERE slug='asset_creation')),
  ('sculpting','Sculpting',              (SELECT id FROM area_of_use WHERE slug='asset_creation')),
  ('rigging','Rigging',                  (SELECT id FROM area_of_use WHERE slug='asset_creation')),
  ('animation','Animation',              (SELECT id FROM area_of_use WHERE slug='asset_creation')),
  ('vfx','VFX',                          (SELECT id FROM area_of_use WHERE slug='asset_creation')),
  ('sound_design','Sound Design',        (SELECT id FROM area_of_use WHERE slug='audio')),
  ('music_composition','Music Composition',(SELECT id FROM area_of_use WHERE slug='audio')),
  ('audio_implementation','Audio Implementation',(SELECT id FROM area_of_use WHERE slug='audio')),
  ('level_design','Level Design',        (SELECT id FROM area_of_use WHERE slug='world_building')),
  ('terrain','Terrain',                  (SELECT id FROM area_of_use WHERE slug='world_building')),
  ('tilemap','Tilemap',                  (SELECT id FROM area_of_use WHERE slug='world_building')),
  ('world_streaming','World Streaming',  (SELECT id FROM area_of_use WHERE slug='world_building')),
  ('gameplay_scripting','Gameplay Scripting',(SELECT id FROM area_of_use WHERE slug='programming')),
  ('visual_scripting','Visual Scripting',(SELECT id FROM area_of_use WHERE slug='programming')),
  ('shader_authoring','Shader Authoring',(SELECT id FROM area_of_use WHERE slug='programming')),
  ('ai_behaviour','AI Behaviour',        (SELECT id FROM area_of_use WHERE slug='programming')),
  ('physics','Physics',                  (SELECT id FROM area_of_use WHERE slug='programming')),
  ('netcode','Netcode',                  (SELECT id FROM area_of_use WHERE slug='networking')),
  ('backend_services','Backend Services',(SELECT id FROM area_of_use WHERE slug='networking')),
  ('matchmaking','Matchmaking',          (SELECT id FROM area_of_use WHERE slug='networking')),
  ('version_control','Version Control',  (SELECT id FROM area_of_use WHERE slug='production')),
  ('project_management','Project Management',(SELECT id FROM area_of_use WHERE slug='production')),
  ('build_ci','Build / CI',              (SELECT id FROM area_of_use WHERE slug='production')),
  ('localization','Localization',        (SELECT id FROM area_of_use WHERE slug='production')),
  ('analytics','Analytics',              (SELECT id FROM area_of_use WHERE slug='production')),
  ('qa_testing','QA / Testing',          (SELECT id FROM area_of_use WHERE slug='production')),
  ('ui_authoring','UI Authoring',        (SELECT id FROM area_of_use WHERE slug='ui_ux')),
  ('dialogue_narrative','Dialogue / Narrative',(SELECT id FROM area_of_use WHERE slug='ui_ux')),
  ('accessibility','Accessibility',      (SELECT id FROM area_of_use WHERE slug='ui_ux')),
  ('store_publishing','Store Publishing',(SELECT id FROM area_of_use WHERE slug='distribution')),
  ('packaging','Packaging',              (SELECT id FROM area_of_use WHERE slug='distribution')),
  ('live_ops','Live Ops',                (SELECT id FROM area_of_use WHERE slug='distribution'));

-- 2) PLATFORMS & LANGUAGES ------------------------------------------------
INSERT INTO platform (slug, name) VALUES
  ('windows','Windows'), ('macos','macOS'), ('linux','Linux'),
  ('android','Android'), ('ios','iOS'), ('web','Web'),
  ('nintendo-switch','Nintendo Switch'),
  ('playstation','PlayStation'), ('xbox','Xbox');

INSERT INTO language (slug, name) VALUES
  ('gdscript','GDScript'), ('csharp','C#'), ('cpp','C++'), ('python','Python'),
  ('lua','Lua'), ('javascript','JavaScript'), ('rust','Rust'), ('gml','GameMaker Language');

-- 3) TOOLS ----------------------------------------------------------------
INSERT INTO tool (slug, name, type, summary, has_built_in_editor,
                  licensing_model, licensing_note,
                  confirmed_commercial_titles_count, confirmed_titles_as_of, confirmed_titles_source)
VALUES
  -- ---- Game engines --------------------------------------------------
  ('godot','Godot Engine','game_engine',
   'Free, open-source 2D/3D game engine with its own editor and the GDScript language.',
   true,'free_open_source','MIT licensed',
   1200,'2026-01-01','illustrative placeholder'),
  ('unity','Unity','game_engine',
   'Cross-platform 2D/3D engine with a C# scripting workflow and a large asset ecosystem.',
   true,'tiered','Free Personal tier under $200k annual revenue/funding; paid Pro and Enterprise seat subscriptions above',
   5000,'2026-01-01','illustrative placeholder'),
  ('unreal-engine','Unreal Engine','game_engine',
   'High-fidelity 2D/3D engine with C++ and Blueprint visual scripting, aimed at real-time 3D.',
   true,'royalty_based','Free to use; 5% royalty on lifetime gross product revenue over $1M; Epic Games Store and Fab sales exempt',
   3000,'2026-01-01','illustrative placeholder'),
  ('gamemaker','GameMaker','game_engine',
   'Beginner-friendly 2D engine using its own GML language plus a drag-and-drop visual workflow.',
   true,'tiered','Free for non-commercial use (non-console); one-time Professional license for commercial; Enterprise subscription for console',
   900,'2026-01-01','illustrative placeholder'),
  ('construct-3','Construct 3','game_engine',
   'Browser-based, no-code 2D engine driven by event sheets, with optional JavaScript.',
   true,'subscription','Subscription license; runs in the browser',
   400,'2026-01-01','illustrative placeholder'),
  ('gdevelop','GDevelop','game_engine',
   'Open-source, no-code 2D engine using event-based logic; exports to many platforms.',
   true,'free_open_source','MIT licensed',
   200,'2026-01-01','illustrative placeholder'),
  ('defold','Defold','game_engine',
   'Free, cross-platform 2D/3D engine scripted in Lua, with a small runtime footprint.',
   true,'free_open_source','Defold License (modified Apache 2.0)',
   150,'2026-01-01','illustrative placeholder'),
  ('renpy','Ren''Py','game_engine',
   'Visual-novel engine using a Python-based scripting language; built on top of Pygame.',
   true,'free_open_source','MIT licensed',
   500,'2026-01-01','illustrative placeholder'),
  ('twine','Twine','game_engine',
   'Open-source tool for building branching, choice-based interactive fiction as HTML.',
   true,'free_open_source','GPL licensed',
   NULL,NULL,NULL),
  ('rpg-maker','RPG Maker','game_engine',
   'Low-code engine for tile-based JRPGs with a database-driven editor and JavaScript plugins.',
   true,'paid_one_time','Per-version perpetual license (e.g. RPG Maker MZ)',
   NULL,NULL,NULL),

  -- ---- Frameworks / libraries ----------------------------------------
  ('pygame','Pygame','framework_library',
   'Python library for writing games on top of SDL; low-level building blocks, no editor.',
   false,'free_open_source','LGPL licensed',
   NULL,NULL,NULL),
  ('love2d','LÖVE','framework_library',
   'Lua framework for 2D games built on SDL; code-first with no bundled editor.',
   false,'free_open_source','zlib licensed',
   NULL,NULL,NULL),
  ('monogame','MonoGame','framework_library',
   'Open-source C# framework (an XNA successor) for building cross-platform games in code.',
   false,'free_open_source','MIT / Ms-PL licensed',
   NULL,NULL,NULL),
  ('phaser','Phaser','framework_library',
   'Open-source JavaScript/TypeScript framework for 2D HTML5 games that run in the browser.',
   false,'free_open_source','MIT licensed',
   NULL,NULL,NULL),
  ('bevy','Bevy','framework_library',
   'Data-driven Rust game engine/framework built around an ECS; code-first, no bundled editor.',
   false,'free_open_source','MIT / Apache-2.0 licensed',
   NULL,NULL,NULL),

  -- ---- Asset creators ------------------------------------------------
  ('blender','Blender','asset_creator',
   'Open-source 3D creation suite for modelling, sculpting, rigging, animation and rendering.',
   true,'free_open_source','GPL licensed',
   NULL,NULL,NULL),
  ('aseprite','Aseprite','asset_creator',
   'Focused editor for pixel art and animated sprites, with Lua scripting.',
   true,'paid_one_time','Paid binaries; source available under a non-free EULA',
   NULL,NULL,NULL),
  ('krita','Krita','asset_creator',
   'Open-source digital painting application for 2D art, concept work and textures.',
   true,'free_open_source','GPL licensed',
   NULL,NULL,NULL),
  ('substance-painter','Adobe Substance 3D Painter','asset_creator',
   'A 3D painting tool for authoring PBR textures and materials directly on models.',
   true,'subscription','Adobe subscription; a perpetual Steam edition is also available',
   NULL,NULL,NULL),
  ('spine','Spine','asset_creator',
   '2D skeletal animation tool that rigs and animates sprites for runtime playback.',
   true,'paid_one_time','Perpetual license; Essential and Professional editions',
   NULL,NULL,NULL),
  ('tiled','Tiled','asset_creator',
   'Open-source map editor for tile-based levels, exporting TMX/TMJ for many engines.',
   true,'free_open_source','GPL licensed; donation-supported',
   NULL,NULL,NULL),

  -- ---- Audio middleware ----------------------------------------------
  ('fmod','FMOD','middleware',
   'Adaptive audio engine and authoring tool (FMOD Studio) that plugs into game engines.',
   true,'tiered','Free tier for small budgets; paid tiers above revenue thresholds',
   NULL,NULL,NULL),
  ('wwise','Wwise','middleware',
   'Interactive audio authoring tool and engine that integrates with game engines.',
   true,'tiered','Free tier within limits; commercial licensing above revenue/project thresholds',
   NULL,NULL,NULL),

  -- ---- Asset marketplaces (separate entities from any engine) --------
  ('itch-io','itch.io','asset_marketplace',
   'Open marketplace/storefront for indie games and game assets; engine-agnostic.',
   false,'free_proprietary','Free to use; optional creator-set revenue share',
   NULL,NULL,NULL),
  ('unity-asset-store','Unity Asset Store','asset_marketplace',
   'Unity''s first-party marketplace for engine plugins, art, audio and project templates.',
   false,'free_proprietary','Free to use; paid and free assets; revenue share on sales',
   NULL,NULL,NULL),
  ('fab','Fab','asset_marketplace',
   'Epic''s unified content marketplace, the successor to the Unreal Engine Marketplace and others.',
   false,'free_proprietary','Free to use; paid and free assets; 88/12 revenue split',
   NULL,NULL,NULL);

-- 4) STRUCTURED LINKS -----------------------------------------------------
INSERT INTO tool_link (tool_id, type, url) VALUES
  ((SELECT id FROM tool WHERE slug='godot'),'WEBSITE','https://godotengine.org'),
  ((SELECT id FROM tool WHERE slug='godot'),'DOCS','https://docs.godotengine.org'),
  ((SELECT id FROM tool WHERE slug='godot'),'SOURCE_REPO','https://github.com/godotengine/godot'),
  ((SELECT id FROM tool WHERE slug='unity'),'WEBSITE','https://unity.com'),
  ((SELECT id FROM tool WHERE slug='unity'),'DOCS','https://docs.unity3d.com'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),'WEBSITE','https://www.unrealengine.com'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),'DOCS','https://dev.epicgames.com/documentation/unreal-engine'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),'WEBSITE','https://gamemaker.io'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),'DOCS','https://manual.gamemaker.io'),
  ((SELECT id FROM tool WHERE slug='construct-3'),'WEBSITE','https://www.construct.net'),
  ((SELECT id FROM tool WHERE slug='construct-3'),'DOCS','https://www.construct.net/en/make-games/manuals/construct-3'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),'WEBSITE','https://gdevelop.io'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),'SOURCE_REPO','https://github.com/4ian/GDevelop'),
  ((SELECT id FROM tool WHERE slug='defold'),'WEBSITE','https://defold.com'),
  ((SELECT id FROM tool WHERE slug='defold'),'SOURCE_REPO','https://github.com/defold/defold'),
  ((SELECT id FROM tool WHERE slug='renpy'),'WEBSITE','https://www.renpy.org'),
  ((SELECT id FROM tool WHERE slug='renpy'),'DOCS','https://www.renpy.org/doc/html/'),
  ((SELECT id FROM tool WHERE slug='twine'),'WEBSITE','https://twinery.org'),
  ((SELECT id FROM tool WHERE slug='twine'),'SOURCE_REPO','https://github.com/klembot/twinejs'),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),'WEBSITE','https://www.rpgmakerweb.com'),
  ((SELECT id FROM tool WHERE slug='pygame'),'WEBSITE','https://www.pygame.org'),
  ((SELECT id FROM tool WHERE slug='love2d'),'WEBSITE','https://love2d.org'),
  ((SELECT id FROM tool WHERE slug='love2d'),'SOURCE_REPO','https://github.com/love2d/love'),
  ((SELECT id FROM tool WHERE slug='monogame'),'WEBSITE','https://monogame.net'),
  ((SELECT id FROM tool WHERE slug='monogame'),'SOURCE_REPO','https://github.com/MonoGame/MonoGame'),
  ((SELECT id FROM tool WHERE slug='phaser'),'WEBSITE','https://phaser.io'),
  ((SELECT id FROM tool WHERE slug='phaser'),'SOURCE_REPO','https://github.com/phaserjs/phaser'),
  ((SELECT id FROM tool WHERE slug='bevy'),'WEBSITE','https://bevy.org'),
  ((SELECT id FROM tool WHERE slug='bevy'),'SOURCE_REPO','https://github.com/bevyengine/bevy'),
  ((SELECT id FROM tool WHERE slug='blender'),'WEBSITE','https://www.blender.org'),
  ((SELECT id FROM tool WHERE slug='blender'),'DOCS','https://docs.blender.org'),
  ((SELECT id FROM tool WHERE slug='aseprite'),'WEBSITE','https://www.aseprite.org'),
  ((SELECT id FROM tool WHERE slug='krita'),'WEBSITE','https://krita.org'),
  ((SELECT id FROM tool WHERE slug='krita'),'SOURCE_REPO','https://invent.kde.org/graphics/krita'),
  ((SELECT id FROM tool WHERE slug='substance-painter'),'WEBSITE','https://www.adobe.com/products/substance3d-painter.html'),
  ((SELECT id FROM tool WHERE slug='spine'),'WEBSITE','http://esotericsoftware.com'),
  ((SELECT id FROM tool WHERE slug='tiled'),'WEBSITE','https://www.mapeditor.org'),
  ((SELECT id FROM tool WHERE slug='tiled'),'SOURCE_REPO','https://github.com/mapeditor/tiled'),
  ((SELECT id FROM tool WHERE slug='fmod'),'WEBSITE','https://www.fmod.com'),
  ((SELECT id FROM tool WHERE slug='wwise'),'WEBSITE','https://www.audiokinetic.com/products/wwise/'),
  ((SELECT id FROM tool WHERE slug='itch-io'),'WEBSITE','https://itch.io'),
  ((SELECT id FROM tool WHERE slug='unity-asset-store'),'WEBSITE','https://assetstore.unity.com'),
  ((SELECT id FROM tool WHERE slug='fab'),'WEBSITE','https://www.fab.com');

-- 5) TOOL <-> AREA OF USE -------------------------------------------------
-- Tag the most specific leaf; a general engine may also carry 'development'.
INSERT INTO tool_area_of_use (tool_id, area_of_use_id) VALUES
  ((SELECT id FROM tool WHERE slug='godot'),  (SELECT id FROM area_of_use WHERE slug='development')),
  ((SELECT id FROM tool WHERE slug='godot'),  (SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='unity'),  (SELECT id FROM area_of_use WHERE slug='development')),
  ((SELECT id FROM tool WHERE slug='unity'),  (SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM area_of_use WHERE slug='development')),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM area_of_use WHERE slug='visual_scripting')),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM area_of_use WHERE slug='development')),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM area_of_use WHERE slug='development')),
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM area_of_use WHERE slug='visual_scripting')),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM area_of_use WHERE slug='development')),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM area_of_use WHERE slug='visual_scripting')),
  ((SELECT id FROM tool WHERE slug='defold'), (SELECT id FROM area_of_use WHERE slug='development')),
  ((SELECT id FROM tool WHERE slug='defold'), (SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='renpy'),  (SELECT id FROM area_of_use WHERE slug='dialogue_narrative')),
  ((SELECT id FROM tool WHERE slug='renpy'),  (SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='twine'),  (SELECT id FROM area_of_use WHERE slug='dialogue_narrative')),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM area_of_use WHERE slug='development')),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM area_of_use WHERE slug='level_design')),
  ((SELECT id FROM tool WHERE slug='pygame'), (SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='love2d'), (SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='phaser'), (SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='bevy'),   (SELECT id FROM area_of_use WHERE slug='development')),
  ((SELECT id FROM tool WHERE slug='bevy'),   (SELECT id FROM area_of_use WHERE slug='gameplay_scripting')),
  ((SELECT id FROM tool WHERE slug='blender'),(SELECT id FROM area_of_use WHERE slug='3d_modelling')),
  ((SELECT id FROM tool WHERE slug='blender'),(SELECT id FROM area_of_use WHERE slug='animation')),
  ((SELECT id FROM tool WHERE slug='aseprite'),(SELECT id FROM area_of_use WHERE slug='pixel_art')),
  ((SELECT id FROM tool WHERE slug='krita'),  (SELECT id FROM area_of_use WHERE slug='2d_art')),
  ((SELECT id FROM tool WHERE slug='krita'),  (SELECT id FROM area_of_use WHERE slug='texturing')),
  ((SELECT id FROM tool WHERE slug='substance-painter'),(SELECT id FROM area_of_use WHERE slug='texturing')),
  ((SELECT id FROM tool WHERE slug='spine'),  (SELECT id FROM area_of_use WHERE slug='animation')),
  ((SELECT id FROM tool WHERE slug='tiled'),  (SELECT id FROM area_of_use WHERE slug='tilemap')),
  ((SELECT id FROM tool WHERE slug='tiled'),  (SELECT id FROM area_of_use WHERE slug='level_design')),
  ((SELECT id FROM tool WHERE slug='fmod'),   (SELECT id FROM area_of_use WHERE slug='audio_implementation')),
  ((SELECT id FROM tool WHERE slug='wwise'),  (SELECT id FROM area_of_use WHERE slug='audio_implementation')),
  ((SELECT id FROM tool WHERE slug='wwise'),  (SELECT id FROM area_of_use WHERE slug='sound_design')),
  ((SELECT id FROM tool WHERE slug='itch-io'),(SELECT id FROM area_of_use WHERE slug='store_publishing'));
  -- Note: unity-asset-store and fab are asset marketplaces; the taxonomy has
  -- no "asset acquisition" leaf, so they are intentionally left untagged.

-- 6) TOOL <-> PLATFORM (role) ---------------------------------------------
INSERT INTO tool_platform (tool_id, platform_id, role) VALUES
  -- Godot
  ((SELECT id FROM tool WHERE slug='godot'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='godot'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='godot'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='godot'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='godot'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='godot'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='godot'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='godot'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='godot'),(SELECT id FROM platform WHERE slug='web'),'TARGET'),
  -- Unity
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='web'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='nintendo-switch'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='playstation'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unity'),(SELECT id FROM platform WHERE slug='xbox'),'TARGET'),
  -- Unreal Engine
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='nintendo-switch'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='playstation'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM platform WHERE slug='xbox'),'TARGET'),
  -- GameMaker
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='web'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='nintendo-switch'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='playstation'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM platform WHERE slug='xbox'),'TARGET'),
  -- Construct 3 (browser-based; also installable)
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM platform WHERE slug='web'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM platform WHERE slug='web'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  -- GDevelop
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM platform WHERE slug='web'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM platform WHERE slug='web'),'TARGET'),
  -- Defold
  ((SELECT id FROM tool WHERE slug='defold'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='defold'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='defold'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='defold'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='defold'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='defold'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='defold'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='defold'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='defold'),(SELECT id FROM platform WHERE slug='web'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='defold'),(SELECT id FROM platform WHERE slug='nintendo-switch'),'TARGET'),
  -- Ren'Py
  ((SELECT id FROM tool WHERE slug='renpy'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='renpy'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='renpy'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='renpy'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='renpy'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='renpy'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='renpy'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='renpy'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  -- Twine
  ((SELECT id FROM tool WHERE slug='twine'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='twine'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='twine'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='twine'),(SELECT id FROM platform WHERE slug='web'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='twine'),(SELECT id FROM platform WHERE slug='web'),'TARGET'),
  -- RPG Maker
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM platform WHERE slug='web'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM platform WHERE slug='nintendo-switch'),'TARGET'),
  -- Pygame
  ((SELECT id FROM tool WHERE slug='pygame'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='pygame'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='pygame'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='pygame'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='pygame'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='pygame'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  -- LÖVE
  ((SELECT id FROM tool WHERE slug='love2d'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='love2d'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='love2d'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='love2d'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='love2d'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='love2d'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='love2d'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='love2d'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  -- MonoGame
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='android'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='ios'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='nintendo-switch'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='playstation'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM platform WHERE slug='xbox'),'TARGET'),
  -- Phaser
  ((SELECT id FROM tool WHERE slug='phaser'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='phaser'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='phaser'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='phaser'),(SELECT id FROM platform WHERE slug='web'),'TARGET'),
  -- Bevy
  ((SELECT id FROM tool WHERE slug='bevy'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='bevy'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='bevy'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='bevy'),(SELECT id FROM platform WHERE slug='windows'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='bevy'),(SELECT id FROM platform WHERE slug='macos'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='bevy'),(SELECT id FROM platform WHERE slug='linux'),'TARGET'),
  ((SELECT id FROM tool WHERE slug='bevy'),(SELECT id FROM platform WHERE slug='web'),'TARGET'),
  -- Asset creators (host-only DCC / editor apps)
  ((SELECT id FROM tool WHERE slug='blender'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='blender'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='blender'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='aseprite'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='aseprite'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='aseprite'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='krita'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='krita'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='krita'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='substance-painter'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='substance-painter'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='substance-painter'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='spine'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='spine'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='spine'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='tiled'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='tiled'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='tiled'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  -- Audio middleware (authoring apps)
  ((SELECT id FROM tool WHERE slug='fmod'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='fmod'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='fmod'),(SELECT id FROM platform WHERE slug='linux'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='wwise'),(SELECT id FROM platform WHERE slug='windows'),'HOST_OS'),
  ((SELECT id FROM tool WHERE slug='wwise'),(SELECT id FROM platform WHERE slug='macos'),'HOST_OS');

-- 7) TOOL <-> LANGUAGE ----------------------------------------------------
INSERT INTO tool_language (tool_id, language_id) VALUES
  ((SELECT id FROM tool WHERE slug='godot'),  (SELECT id FROM language WHERE slug='gdscript')),
  ((SELECT id FROM tool WHERE slug='godot'),  (SELECT id FROM language WHERE slug='csharp')),
  ((SELECT id FROM tool WHERE slug='godot'),  (SELECT id FROM language WHERE slug='cpp')),
  ((SELECT id FROM tool WHERE slug='unity'),  (SELECT id FROM language WHERE slug='csharp')),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM language WHERE slug='cpp')),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM language WHERE slug='gml')),
  ((SELECT id FROM tool WHERE slug='construct-3'),(SELECT id FROM language WHERE slug='javascript')),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM language WHERE slug='javascript')),
  ((SELECT id FROM tool WHERE slug='defold'), (SELECT id FROM language WHERE slug='lua')),
  ((SELECT id FROM tool WHERE slug='renpy'),  (SELECT id FROM language WHERE slug='python')),
  ((SELECT id FROM tool WHERE slug='rpg-maker'),(SELECT id FROM language WHERE slug='javascript')),
  ((SELECT id FROM tool WHERE slug='pygame'), (SELECT id FROM language WHERE slug='python')),
  ((SELECT id FROM tool WHERE slug='love2d'), (SELECT id FROM language WHERE slug='lua')),
  ((SELECT id FROM tool WHERE slug='monogame'),(SELECT id FROM language WHERE slug='csharp')),
  ((SELECT id FROM tool WHERE slug='phaser'), (SELECT id FROM language WHERE slug='javascript')),
  ((SELECT id FROM tool WHERE slug='bevy'),   (SELECT id FROM language WHERE slug='rust')),
  ((SELECT id FROM tool WHERE slug='blender'),(SELECT id FROM language WHERE slug='python')),
  ((SELECT id FROM tool WHERE slug='aseprite'),(SELECT id FROM language WHERE slug='lua')),
  ((SELECT id FROM tool WHERE slug='krita'),  (SELECT id FROM language WHERE slug='python')),
  ((SELECT id FROM tool WHERE slug='substance-painter'),(SELECT id FROM language WHERE slug='python'));

-- 8) TYPED EDGES (tool-to-tool relationships) -----------------------------
-- Directional: EXPORTS_TO / PLUGIN_FOR / BUILDS_ON.  Symmetric: PAIRS_WELL_WITH.
INSERT INTO tool_relationship (source_tool_id, target_tool_id, type, note) VALUES
  -- Blender exports assets into the major engines
  ((SELECT id FROM tool WHERE slug='blender'),(SELECT id FROM tool WHERE slug='godot'),
   'EXPORTS_TO','3D assets via glTF 2.0'),
  ((SELECT id FROM tool WHERE slug='blender'),(SELECT id FROM tool WHERE slug='unity'),
   'EXPORTS_TO','3D assets via FBX / glTF'),
  ((SELECT id FROM tool WHERE slug='blender'),(SELECT id FROM tool WHERE slug='unreal-engine'),
   'EXPORTS_TO','3D assets via FBX / glTF'),
  -- Audio middleware plugs into engines
  ((SELECT id FROM tool WHERE slug='fmod'),(SELECT id FROM tool WHERE slug='godot'),
   'PLUGIN_FOR','Integration plugin for adaptive audio'),
  ((SELECT id FROM tool WHERE slug='fmod'),(SELECT id FROM tool WHERE slug='unity'),
   'PLUGIN_FOR','FMOD Studio integration for Unity'),
  ((SELECT id FROM tool WHERE slug='fmod'),(SELECT id FROM tool WHERE slug='unreal-engine'),
   'PLUGIN_FOR','FMOD Studio integration for Unreal'),
  ((SELECT id FROM tool WHERE slug='wwise'),(SELECT id FROM tool WHERE slug='unity'),
   'PLUGIN_FOR','Wwise integration for Unity'),
  ((SELECT id FROM tool WHERE slug='wwise'),(SELECT id FROM tool WHERE slug='unreal-engine'),
   'PLUGIN_FOR','Wwise integration for Unreal'),
  -- Content pipeline tools into engines
  ((SELECT id FROM tool WHERE slug='tiled'),(SELECT id FROM tool WHERE slug='godot'),
   'EXPORTS_TO','Tilemaps via TMX / TMJ'),
  ((SELECT id FROM tool WHERE slug='spine'),(SELECT id FROM tool WHERE slug='unity'),
   'PLUGIN_FOR','spine-unity runtime for skeletal animation'),
  ((SELECT id FROM tool WHERE slug='substance-painter'),(SELECT id FROM tool WHERE slug='unity'),
   'EXPORTS_TO','PBR texture maps'),
  ((SELECT id FROM tool WHERE slug='substance-painter'),(SELECT id FROM tool WHERE slug='unreal-engine'),
   'EXPORTS_TO','PBR texture maps'),
  -- Ren'Py builds on Pygame
  ((SELECT id FROM tool WHERE slug='renpy'),(SELECT id FROM tool WHERE slug='pygame'),
   'BUILDS_ON','Ren''Py runs on the Pygame/SDL layer'),
  -- Marketplace variants linked to their engines (kept as separate entities)
  ((SELECT id FROM tool WHERE slug='unity-asset-store'),(SELECT id FROM tool WHERE slug='unity'),
   'PAIRS_WELL_WITH','First-party asset marketplace for Unity'),
  ((SELECT id FROM tool WHERE slug='fab'),(SELECT id FROM tool WHERE slug='unreal-engine'),
   'PAIRS_WELL_WITH','Epic''s asset marketplace; integrates with Unreal Engine'),
  ((SELECT id FROM tool WHERE slug='fab'),(SELECT id FROM tool WHERE slug='unity'),
   'PAIRS_WELL_WITH','Fab is engine-agnostic in some asset categories'),
  -- Editorial pairings
  ((SELECT id FROM tool WHERE slug='blender'),(SELECT id FROM tool WHERE slug='godot'),
   'PAIRS_WELL_WITH','Common free/open-source 3D + engine workflow'),
  ((SELECT id FROM tool WHERE slug='aseprite'),(SELECT id FROM tool WHERE slug='godot'),
   'PAIRS_WELL_WITH','Popular pixel-art + 2D engine workflow'),
  ((SELECT id FROM tool WHERE slug='tiled'),(SELECT id FROM tool WHERE slug='love2d'),
   'PAIRS_WELL_WITH','Common tilemap workflow for LÖVE via loaders'),
  ((SELECT id FROM tool WHERE slug='phaser'),(SELECT id FROM tool WHERE slug='itch-io'),
   'PAIRS_WELL_WITH','HTML5 games are widely published on itch.io'),
  ((SELECT id FROM tool WHERE slug='gdevelop'),(SELECT id FROM tool WHERE slug='itch-io'),
   'PAIRS_WELL_WITH','No-code games are widely published on itch.io'),
  ((SELECT id FROM tool WHERE slug='twine'),(SELECT id FROM tool WHERE slug='itch-io'),
   'PAIRS_WELL_WITH','Interactive fiction is widely published on itch.io'),
  ((SELECT id FROM tool WHERE slug='itch-io'),(SELECT id FROM tool WHERE slug='renpy'),
   'PAIRS_WELL_WITH','Visual novels are widely published and sold on itch.io');

-- 9) GAMES + SHARED LINKS -------------------------------------------------
INSERT INTO game (slug, name, developer, publisher, release_year) VALUES
  ('brotato','Brotato','Blobfish','Blobfish',2023),
  ('buckshot-roulette','Buckshot Roulette','Mike Klubnika','Critical Reflex',2024),
  ('hollow-knight','Hollow Knight','Team Cherry','Team Cherry',2017),
  ('cuphead','Cuphead','Studio MDHR','Studio MDHR',2017),
  ('fortnite','Fortnite','Epic Games','Epic Games',2017),
  ('undertale','Undertale','Toby Fox','Toby Fox',2015),
  ('katana-zero','Katana ZERO','Askiisoft','Devolver Digital',2019),
  ('doki-doki-literature-club','Doki Doki Literature Club!','Team Salvato','Team Salvato',2017),
  ('stardew-valley','Stardew Valley','ConcernedApe','ConcernedApe',2016),
  ('vampire-survivors','Vampire Survivors','poncle','poncle',2022);

-- Store links use well-known Steam app ids; curator should verify each.
INSERT INTO game_store_link (game_id, store_label, url) VALUES
  ((SELECT id FROM game WHERE slug='brotato'),'Steam','https://store.steampowered.com/app/1942280/'),
  ((SELECT id FROM game WHERE slug='hollow-knight'),'Steam','https://store.steampowered.com/app/367520/'),
  ((SELECT id FROM game WHERE slug='cuphead'),'Steam','https://store.steampowered.com/app/268910/'),
  ((SELECT id FROM game WHERE slug='undertale'),'Steam','https://store.steampowered.com/app/391540/'),
  ((SELECT id FROM game WHERE slug='katana-zero'),'Steam','https://store.steampowered.com/app/460950/'),
  ((SELECT id FROM game WHERE slug='doki-doki-literature-club'),'Steam','https://store.steampowered.com/app/698780/'),
  ((SELECT id FROM game WHERE slug='stardew-valley'),'Steam','https://store.steampowered.com/app/413150/'),
  ((SELECT id FROM game WHERE slug='vampire-survivors'),'Steam','https://store.steampowered.com/app/1794680/');

INSERT INTO tool_game (tool_id, game_id) VALUES
  ((SELECT id FROM tool WHERE slug='godot'),    (SELECT id FROM game WHERE slug='brotato')),
  ((SELECT id FROM tool WHERE slug='godot'),    (SELECT id FROM game WHERE slug='buckshot-roulette')),
  ((SELECT id FROM tool WHERE slug='unity'),    (SELECT id FROM game WHERE slug='hollow-knight')),
  ((SELECT id FROM tool WHERE slug='unity'),    (SELECT id FROM game WHERE slug='cuphead')),
  ((SELECT id FROM tool WHERE slug='unreal-engine'),(SELECT id FROM game WHERE slug='fortnite')),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM game WHERE slug='undertale')),
  ((SELECT id FROM tool WHERE slug='gamemaker'),(SELECT id FROM game WHERE slug='katana-zero')),
  ((SELECT id FROM tool WHERE slug='renpy'),    (SELECT id FROM game WHERE slug='doki-doki-literature-club')),
  ((SELECT id FROM tool WHERE slug='monogame'), (SELECT id FROM game WHERE slug='stardew-valley')),
  ((SELECT id FROM tool WHERE slug='phaser'),   (SELECT id FROM game WHERE slug='vampire-survivors'));

COMMIT;
